/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UmOkkurRouteImport } from './routes/um-okkur'
import { Route as ThjonustaRouteImport } from './routes/thjonusta'
import { Route as StarfsfolkRouteImport } from './routes/starfsfolk'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as HafaSambandRouteImport } from './routes/hafa-samband'
import { Route as BokaRouteImport } from './routes/boka'
import { Route as IndexRouteImport } from './routes/index'

const UmOkkurRoute = UmOkkurRouteImport.update({
  id: '/um-okkur',
  path: '/um-okkur',
  getParentRoute: () => rootRouteImport,
} as any)
const ThjonustaRoute = ThjonustaRouteImport.update({
  id: '/thjonusta',
  path: '/thjonusta',
  getParentRoute: () => rootRouteImport,
} as any)
const StarfsfolkRoute = StarfsfolkRouteImport.update({
  id: '/starfsfolk',
  path: '/starfsfolk',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const HafaSambandRoute = HafaSambandRouteImport.update({
  id: '/hafa-samband',
  path: '/hafa-samband',
  getParentRoute: () => rootRouteImport,
} as any)
const BokaRoute = BokaRouteImport.update({
  id: '/boka',
  path: '/boka',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/boka': typeof BokaRoute
  '/hafa-samband': typeof HafaSambandRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/starfsfolk': typeof StarfsfolkRoute
  '/thjonusta': typeof ThjonustaRoute
  '/um-okkur': typeof UmOkkurRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/boka': typeof BokaRoute
  '/hafa-samband': typeof HafaSambandRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/starfsfolk': typeof StarfsfolkRoute
  '/thjonusta': typeof ThjonustaRoute
  '/um-okkur': typeof UmOkkurRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/boka': typeof BokaRoute
  '/hafa-samband': typeof HafaSambandRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/starfsfolk': typeof StarfsfolkRoute
  '/thjonusta': typeof ThjonustaRoute
  '/um-okkur': typeof UmOkkurRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/boka'
    | '/hafa-samband'
    | '/sitemap.xml'
    | '/starfsfolk'
    | '/thjonusta'
    | '/um-okkur'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/boka'
    | '/hafa-samband'
    | '/sitemap.xml'
    | '/starfsfolk'
    | '/thjonusta'
    | '/um-okkur'
  id:
    | '__root__'
    | '/'
    | '/boka'
    | '/hafa-samband'
    | '/sitemap.xml'
    | '/starfsfolk'
    | '/thjonusta'
    | '/um-okkur'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BokaRoute: typeof BokaRoute
  HafaSambandRoute: typeof HafaSambandRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  StarfsfolkRoute: typeof StarfsfolkRoute
  ThjonustaRoute: typeof ThjonustaRoute
  UmOkkurRoute: typeof UmOkkurRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/um-okkur': {
      id: '/um-okkur'
      path: '/um-okkur'
      fullPath: '/um-okkur'
      preLoaderRoute: typeof UmOkkurRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/thjonusta': {
      id: '/thjonusta'
      path: '/thjonusta'
      fullPath: '/thjonusta'
      preLoaderRoute: typeof ThjonustaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/starfsfolk': {
      id: '/starfsfolk'
      path: '/starfsfolk'
      fullPath: '/starfsfolk'
      preLoaderRoute: typeof StarfsfolkRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hafa-samband': {
      id: '/hafa-samband'
      path: '/hafa-samband'
      fullPath: '/hafa-samband'
      preLoaderRoute: typeof HafaSambandRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/boka': {
      id: '/boka'
      path: '/boka'
      fullPath: '/boka'
      preLoaderRoute: typeof BokaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BokaRoute: BokaRoute,
  HafaSambandRoute: HafaSambandRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  StarfsfolkRoute: StarfsfolkRoute,
  ThjonustaRoute: ThjonustaRoute,
  UmOkkurRoute: UmOkkurRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
